# Corrected Python script to separate player information from the original data
def separate_player_info_corrected(data):
    transformed_data = []
    for entry in data:
        player_info, fantasy_team = entry
        name_parts = player_info.split(" ", 1)
        name = name_parts[0]
        rest = name_parts[1]
        position, nfl_team = rest.rsplit(", ", 1)
        nfl_team, position = position.split(" ", 1)
        transformed_entry = [name, nfl_team, position, fantasy_team]
        transformed_data.append(transformed_entry)
    return transformed_data

# Sample data (only including a few for demonstration)
data = [
    # Round 1
    ["Justin Jefferson Min, WR", "Whats a King to a God"],
    ["Tyreek Hill Mia, WR", "Shrimp Fried This Rice?"],
    ["Ja'Marr Chase Cin, WR", "Beans Commodities"],
    ["Lamar Jackson Bal, QB", "OceanGate Submarines"],
    ["Christian McCaffrey SF, RB", "James Connor into bed"],
    ["Austin Ekeler LAC, RB", "My Ball Zach Ertz"],
    ["Bijan Robinson Atl, RB", "Miami Ligma"],
    ["Travis Kelce KC, TE", "HohnHomes"],
    ["Saquon Barkley NYG, RB", "Commish Loves Love"],
    ["Stefon Diggs Buf, WR", "We're Allen this Together"],
# Round 2
    ["Nick Chubb Cle, RB", "We're Allen this Together"],
    ["Derrick Henry Ten, RB", "Commish Loves Love"],
    ["CeeDee Lamb Dal, WR", "HohnHomes"],
    ["Davante Adams LV, WR", "Miami Ligma"],
    ["Tony Pollard Dal, RB", "My Ball Zach Ertz"],
    ["Garrett Wilson NYJ, WR", "James Connor into bed"],
    ["Joe Mixon Cin, RB", "OceanGate Submarines"],
    ["A.J. Brown Phi, WR", "Beans Commodities"],
    ["Cooper Kupp LAR, WR", "Shrimp Fried This Rice?"],
    ["Chris Olave NO, WR", "Whats a King to a God"],
    # Round 3
    ["Josh Jacobs LV, RB", "Whats a King to a God"],
    ["Amon-Ra St. Brown Det, WR", "Shrimp Fried This Rice?"],
    ["Jalen Hurts Phi, QB", "Beans Commodities"],
    ["DeVonta Smith Phi, WR", "OceanGate Submarines"],
    ["Calvin Ridley Jax, WR", "James Connor into bed"],
    ["Jaylen Waddle Mia, WR", "My Ball Zach Ertz"],
    ["Tee Higgins Cin, WR", "Miami Ligma"],
    ["Patrick Mahomes KC, QB", "HohnHomes"],
    ["DK Metcalf Sea, WR", "Commish Loves Love"],
    ["Keenan Allen LAC, WR", "We're Allen this Together"],
    # Round 4
    ["Josh Allen Buf, QB", "We're Allen this Together"],
    ["Deebo Samuel SF, WR", "Commish Loves Love"],
    ["Aaron Jones GB, RB", "HohnHomes"],
    ["Travis Etienne Jr. Jax, RB", "Miami Ligma"],
    ["Najee Harris Pit, RB", "My Ball Zach Ertz"],
    ["Mark Andrews Bal, TE", "James Connor into bed"],
    ["Jahmyr Gibbs Det, RB", "OceanGate Submarines"],
    ["Rhamondre Stevenson NE, RB", "Beans Commodities"],
    ["Kenneth Walker III Sea, RB", "Shrimp Fried This Rice?"],
    ["Dameon Pierce Hou, RB", "Whats a King to a God"],
    # Round 5
    ["Amari Cooper Cle, WR", "Whats a King to a God"],
    ["James Conner Ari, RB", "Shrimp Fried This Rice?"],
    ["Rachaad White TB, RB", "Beans Commodities"],
    ["Christian Watson GB, WR", "OceanGate Submarines"],
    ["Miles Sanders Car, RB", "James Connor into bed"],
    ["Joe Burrow Cin, QB", "My Ball Zach Ertz"],
    ["T.J. Hockenson Min, TE", "Miami Ligma"],
    ["Breece Hall NYJ, RB", "HohnHomes"],
    ["Justin Herbert LAC, QB", "Commish Loves Love"],
    ["DeAndre Hopkins Ten, WR", "We're Allen this Together"],
     # Round 6
    ["Darren Waller NYG, TE", "We're Allen this Together"],
    ["Chris Godwin TB, WR", "Commish Loves Love"],
    ["Diontae Johnson Pit, WR", "HohnHomes"],
    ["DJ Moore Chi, WR", "Miami Ligma"],
    ["Alvin Kamara NO, RB", "My Ball Zach Ertz"],
    ["Mike Evans TB, WR", "James Connor into bed"],
    ["Alexander Mattison Min, RB", "OceanGate Submarines"],
    ["James Cook Buf, RB", "Beans Commodities"],
    ["Tyler Lockett Sea, WR", "Shrimp Fried This Rice?"],
    ["Justin Fields Chi, QB", "Whats a King to a God"],
    #Round 7
    ["Brandon Aiyuk SF, WR", "Whats a King to a God"],
    ["Mike Williams LAC, WR", "Shrimp Fried This Rice?"],
    ["Drake London Atl, WR", "Beans Commodities"],
    ["Terry McLaurin Wsh, WR", "OceanGate Submarines"],
    ["Jonathan Taylor Ind, RB", "James Connor into bed"],
    ["Jerry Jeudy Den, WR", "My Ball Zach Ertz"],
    ["Cam Akers Min, RB", "Miami Ligma"],
    ["Marquise Brown Ari, WR", "HohnHomes"],
    ["Kyle Pitts Atl, TE", "Commish Loves Love"],
    ["David Montgomery Det, RB", "We're Allen this Together"],
    # Round 8
    ["George Pickens Pit, WR", "We're Allen this Together"],
    ["Jahan Dotson Wsh, WR", "Commish Loves Love"],
    ["Courtland Sutton Den, WR", "HohnHomes"],
    ["Deshaun Watson Cle, QB", "Miami Ligma"],
    ["George Kittle SF, TE", "My Ball Zach Ertz"],
    ["Trevor Lawrence Jax, QB", "James Connor into bed"],
    ["Dallas Goedert Phi, TE", "OceanGate Submarines"],
    ["Pat Freiermuth Pit, TE", "Beans Commodities"],
    ["Christian Kirk Jax, WR", "Shrimp Fried This Rice?"],
    ["J.K. Dobbins Bal, RB", "Whats a King to a God"],
    # Round 9
    ["Jaxon Smith-Njigba Sea, WR", "Whats a King to a God"],
    ["Kirk Cousins Min, QB", "Shrimp Fried This Rice?"],
    ["Javonte Williams Den, RB", "Beans Commodities"],
    ["Isiah Pacheco KC, RB", "OceanGate Submarines"],
    ["Michael Pittman Jr. Ind, WR", "James Connor into bed"],
    ["Dalvin Cook NYJ, RB", "My Ball Zach Ertz"],
    ["D'Andre Swift Phi, RB", "Miami Ligma"],
    ["David Njoku Cle, TE", "HohnHomes"],
    ["Brandin Cooks Dal, WR", "Commish Loves Love"],
    ["Zay Flowers Bal, WR", "We're Allen this Together"],
    # Round 10
    ["Jamaal Williams NO, RB", "We're Allen this Together"],
    ["Jordan Addison Min, WR", "Commish Loves Love"],
    ["Gabe Davis Buf, WR", "HohnHomes"],
    ["Skyy Moore KC, WR", "Miami Ligma"],
    ["Khalil Herbert Chi, RB", "My Ball Zach Ertz"],
    ["Michael Thomas NO, WR", "James Connor into bed"],
    ["AJ Dillon GB, RB", "OceanGate Submarines"],
    ["JuJu Smith-Schuster NE, WR", "Beans Commodities"],
    ["Quentin Johnston LAC, WR", "Shrimp Fried This Rice?"],
    ["Brian Robinson Jr. Wsh, RB", "Whats a King to a God"],
    # Round 11
    ["Evan Engram Jax, TE", "Whats a King to a God"],
    ["Rashaad Penny Phi, RB", "Shrimp Fried This Rice?"],
    ["49ers D/ST SF, D/ST", "Beans Commodities"],
    ["Antonio Gibson Wsh, RB", "OceanGate Submarines"],
    ["Samaje Perine Den, RB", "James Connor into bed"],
    ["Cole Kmet Chi, TE", "My Ball Zach Ertz"],
    ["Tua Tagovailoa Mia, QB", "Miami Ligma"],
    ["Justin Tucker Bal, K", "HohnHomes"],
    ["Raheem Mostert Mia, RB", "Commish Loves Love"],
    ["Dalton Kincad Buf, TE", "We're Allen this Together"],
    # Round 12
    ["Evan McPherson Cin, K", "We're Allen this Together"],
    ["Jerick McKinnon KC, RB", "Commish Loves Love"],
    ["Jakobi Meyers LV, WR", "HohnHomes"],
    ["Elijah Moore Cle, WR", "Miami Ligma"],
    ["Treylon Burks Ten, WR", "My Ball Zach Ertz"],
    ["Steelers D/ST Pit, D/ST", "James Connor into bed"],
    ["Odell Beckham Jr. Bal, WR", "OceanGate Submarines"],
    ["Ezekiel Elliott NE, RB", "Beans Commodities"],
    ["Saints D/ST NO, D/ST", "Shrimp Fried This Rice?"],
    ["Tyler Higbee LAR, TE", "Whats a King to a God"],
    # Round 13
    ["DJ Chark Jr. Car, WR", "Whats a King to a God"],
    ["Tank Bigsby Jax, RB", "Shrimp Fried This Rice?"],
    ["Jake Elliott Phi, K", "Beans Commodities"],
    ["Dak Prescott Dal, QB", "OceanGate Submarines"],
    ["Adam Thielen Car, WR", "James Connor into bed"],
    ["Michael Gallup Dal, WR", "My Ball Zach Ertz"],
    ["Chigoziem Okonkwo Ten, TE", "Miami Ligma"],
    ["Cowboys D/ST Dal, D/ST", "HohnHomes"],
    ["Nico Collins Hou, WR", "Commish Loves Love"],
    ["Darnell Mooney Chi, WR", "We're Allen this Together"],
    # Round 14
    ["Aaron Rodgers NYJ, QB", "We're Allen this Together"],
    ["Zach Charbonnet Sea, RB", "Commish Loves Love"],
    ["Tyler Allgeier Atl, RB", "HohnHomes"],
    ["Jaylen Warren Pit, RB", "Miami Ligma"],
    ["Geno Smith Sea, QB", "My Ball Zach Ertz"],
    ["Harrison Butker KC, K", "James Connor into bed"],
    ["Daniel Jones NYG, QB", "OceanGate Submarines"],
    ["Allen Lazard NYJ, WR", "Beans Commodities"],
    ["Daniel Carlson LV, K", "Shrimp Fried This Rice?"],
    ["Graham Gano NYG, K", "Whats a King to a God"],
    # Round 15
    ["Tyler Boyd Cin, WR", "Whats a King to a God"],
    ["Jared Goff Det, QB", "Shrimp Fried This Rice?"],
    ["Kenny Pickett Pit, QB", "Beans Commodities"],
    ["Rondale Moore Ari, WR", "OceanGate Submarines"],
    ["K.J. Osborn Min, WR", "James Connor into bed"],
    ["Bills D/ST Buf, D/ST", "My Ball Zach Ertz"],
    ["Dolphins D/ST Mia, D/ST", "Miami Ligma"],
    ["Kenneth Gainwell Phi, RB", "HohnHomes"],
    ["Dalton Schultz Hou, TE", "Commish Loves Love"],
    ["Deuce Vaughn Dal, RB", "We're Allen this Together"],
    # Round 16
    ["Bengals D/ST Cin, D/ST", "We're Allen this Together"],
    ["Browns D/ST Cle, D/ST", "Commish Loves Love"],
    ["Elijah Mitchell SF, RB", "HohnHomes"],
    ["Younghoe Koo Atl, K", "Miami Ligma"],
    ["Cameron Dicker LAC, K", "My Ball Zach Ertz"],
    ["Russell Wilson Den, QB", "James Connor into bed"],
    ["Jets D/ST NYJ, D/ST", "OceanGate Submarines"],
    ["Hunter Renfrow LV, WR", "Beans Commodities"],
    ["Gerald Everett LAC, TE", "Shrimp Fried This Rice?"],
    ["Anthony Richardson Ind, QB", "Whats a King to a God"],
    # Round 17
    ["Patriots D/ST NE, D/ST", "Whats a King to a God"],
    ["Luke Musgrave GB, TE", "Shrimp Fried This Rice?"],
    ["Zach Ertz Ari, TE", "Beans Commodities"],
    ["Jason Myers Sea, K", "OceanGate Submarines"],
    ["Curtis Samuel Wsh, WR", "James Connor into bed"],
    ["Devin Singletary Hou, RB", "My Ball Zach Ertz"],
    ["De'Von Achane Mia, RB", "Miami Ligma"],
    ["Rashod Bateman Bal, WR", "HohnHomes"],
    ["Tyler Bass Buf, K", "Commish Loves Love"],
    ["Damien Harris Buf, RB", "We're Allen this Together"],
  ];

# Run the function on the sample data
separated_data_corrected = separate_player_info_corrected(data)
print(separated_data_corrected)
